# SPDX-FileCopyrightText: 2026 JWP Consulting GK
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1

[[annotations]]
path = ["apple-touch-icon.png", "favicon.ico"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 JWP Consulting GK"
SPDX-License-Identifier = "AGPL-3.0-or-later"
